"""New table SocialAccount

Revision ID: 2a3a213d9b4b
Revises: 94fe1abd9fe6
Create Date: 2022-03-14 20:09:53.297629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3a213d9b4b'
down_revision = '94fe1abd9fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'role', ['id'])
    op.create_unique_constraint(None, 'success_history', ['id'])
    op.drop_constraint('user_social_id_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['id'])
    op.drop_column('user', 'social_id')
    op.create_unique_constraint(None, 'user_role', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='unique')
    op.add_column('user', sa.Column('social_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_social_id_key', 'user', ['social_id'])
    op.drop_constraint(None, 'success_history', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    # ### end Alembic commands ###
