"""partition

Revision ID: 99be77b6608e
Revises: 535484d68c91
Create Date: 2022-03-15 20:41:19.129762

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "99be77b6608e"
down_revision = "535484d68c91"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "role", ["id"])
    op.create_unique_constraint(None, "user", ["id"])
    op.create_unique_constraint(None, "user_role", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_role", type_="unique")
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "role", type_="unique")
    # ### end Alembic commands ###
