"""Initial migration.

Revision ID: b2e305b83b5c
Revises: 94fe1abd9fe6
Create Date: 2022-03-14 15:16:13.476387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e305b83b5c'
down_revision = '94fe1abd9fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'role', ['id'])
    op.add_column('success_history', sa.Column('ip_address', sa.String(length=100), nullable=True))
    op.add_column('success_history', sa.Column('user_agent', sa.Text(), nullable=False))
    op.add_column('success_history', sa.Column('platform', sa.Text(), nullable=False))
    op.add_column('success_history', sa.Column('browser', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'success_history', ['id'])
    op.create_unique_constraint(None, 'success_history', ['id', 'platform'])
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user_role', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    op.drop_constraint(None, 'success_history', type_='unique')
    op.drop_constraint(None, 'success_history', type_='unique')
    op.drop_column('success_history', 'browser')
    op.drop_column('success_history', 'platform')
    op.drop_column('success_history', 'user_agent')
    op.drop_column('success_history', 'ip_address')
    op.drop_constraint(None, 'role', type_='unique')
    # ### end Alembic commands ###
