"""Initial migration.

Revision ID: d11d7a049145
Revises: 
Create Date: 2022-03-14 19:55:38.825015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd11d7a049145'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_role', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('user_role', 'role_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_constraint('user_role_user_id_role_id_key', 'user_role', type_='unique')
    op.create_unique_constraint('user_role_pk', 'user_role', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_role_pk', 'user_role', type_='unique')
    op.create_unique_constraint('user_role_user_id_role_id_key', 'user_role', ['user_id', 'role_id'])
    op.alter_column('user_role', 'role_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('user_role', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
